version: 2

project_name: paddleocr-cli

before:
  hooks:
    - go mod tidy

builds:
  - id: paddleocr-cli
    main: ./cmd/paddleocr-cli
    binary: paddleocr-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  # 带版本号的归档（用于版本追踪）
  - id: versioned
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - README.md
  # 不带版本号的归档（方便安装脚本使用 latest URL）
  - id: latest
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: Explorer1092
    name: paddleocr_cli
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
