version: 2

project_name: paddleocr-cli

before:
  hooks:
    - go mod tidy

builds:
  - id: paddleocr-cli
    main: ./cmd/paddleocr-cli
    binary: paddleocr-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: Explorer1092
    name: paddleocr_cli
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"

brews:
  - name: paddleocr-cli
    repository:
      owner: Explorer1092
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    skip_upload: auto
    directory: Formula
    homepage: "https://github.com/Explorer1092/paddleocr_cli"
    description: "A command-line tool for OCR using PaddleOCR AI Studio API"
    license: "MIT"
    install: |
      bin.install "paddleocr-cli"
    test: |
      system "#{bin}/paddleocr-cli", "--version"
